// generateChildrenSeed.cjs
// Run: node scripts/generateChildrenSeed.cjs
// Reads "Children List Only.csv" and writes src/seedChildren.ts

const fs = require('fs');
const path = require('path');

const CSV_PATH = 'C:\\Users\\Admin\\Downloads\\Children List Only.csv';
const OUT_PATH = path.join(__dirname, '..', 'src', 'seedChildren.ts');

function parseCSVLine(line) {
  const result = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(cur.trim());
      cur = '';
    } else {
      cur += ch;
    }
  }
  result.push(cur.trim());
  return result;
}

// Convert M/D/YYYY to YYYY-MM-DD
function toISO(dateStr) {
  if (!dateStr || !dateStr.trim()) return '';
  const parts = dateStr.trim().split('/');
  if (parts.length !== 3) return '';
  const [m, d, y] = parts;
  if (!m || !d || !y) return '';
  return `${y.padStart(4,'0')}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`;
}

function calcAge(dobISO) {
  if (!dobISO) return -1;
  const dob = new Date(dobISO);
  const today = new Date();
  let age = today.getFullYear() - dob.getFullYear();
  const m = today.getMonth() - dob.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < dob.getDate())) age--;
  return age;
}

function levelFromAge(age) {
  if (age <= 2) return 'Nursery';
  if (age <= 4) return 'Pre-K';
  if (age === 5) return 'Kindergarten';
  if (age <= 10) return 'Elementary';
  if (age <= 13) return 'Middle School';
  if (age <= 17) return 'High School';
  return 'Young Adult';
}

const raw = fs.readFileSync(CSV_PATH, 'utf8');
const lines = raw.split(/\r?\n/).filter(l => l.trim());
const headers = parseCSVLine(lines[0]);

console.log('Headers:', headers);
console.log('Total data rows:', lines.length - 1);

const kidRecords = [];
const memberRecords = [];

lines.slice(1).forEach((line, i) => {
  const cols = parseCSVLine(line);
  const get = (name) => {
    const idx = headers.indexOf(name);
    return idx >= 0 ? (cols[idx] || '').trim() : '';
  };

  const first = get('First Name');
  const last = get('Last Name');
  if (!first || !last) return;

  const dob = toISO(get('Birthdate'));
  const status = get('Status') || 'Active';
  const age = calcAge(dob);
  const grade = age >= 0 ? levelFromAge(age) : '';

  // Education/Kids module record
  kidRecords.push({
    id: 800000 + i,
    first,
    last,
    dob,
    grade,
    classroomId: null,
    parentName: '',
    parentPhone: '',
    parentMemberId: null,
    allergies: [],
    medical: [],
    medicalNotes: '',
    emergencyPickup: '',
    status,
  });

  // Members directory record
  memberRecords.push({
    id: 850000 + i,
    first,
    last,
    type: 'Member',
    status,
    role: '',
    joined: '2026-05-19',
    family: '',
    familyId: null,
    notes: '',
    phone: '',
    email: '',
    gender: '',
    birthday: dob,
    anniversary: '',
    spouseName: '',
    children: [],
    emergencyName: '',
    emergencyPhone: '',
    emergencyRelation: '',
    baptismDate: '',
    salvationDate: '',
    allergies: [],
    medical: [],
    medicalNotes: '',
    occupation: '',
    employer: '',
    address: { street: '', city: '', state: get('State') || '', zip: '' },
    addedBy: 'CSV Import',
    addedDate: '2026-05-19',
  });
});

console.log('Valid records:', kidRecords.length);

const ts = `// AUTO-GENERATED by scripts/generateChildrenSeed.cjs — do not edit manually
// Source: Children List Only.csv (${kidRecords.length} children)
export const SEED_CHILDREN: any[] = ${JSON.stringify(kidRecords, null, 0)};
export const SEED_CHILDREN_AS_MEMBERS: any[] = ${JSON.stringify(memberRecords, null, 0)};
`;

fs.writeFileSync(OUT_PATH, ts, 'utf8');
console.log('Written to', OUT_PATH);
