// generateMemberSeed.js
// Run: node scripts/generateMemberSeed.js
// Reads Adults List.csv and writes src/seedMembers.ts

const fs = require('fs');
const path = require('path');

const CSV_PATH = 'C:\\Users\\Admin\\Downloads\\Adults List.csv';
const OUT_PATH = path.join(__dirname, '..', 'src', 'seedMembers.ts');

function parseCSVLine(line) {
  const result = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(cur.trim());
      cur = '';
    } else {
      cur += ch;
    }
  }
  result.push(cur.trim());
  return result;
}

// Convert M/D/YYYY or MM/DD/YYYY to YYYY-MM-DD
function toISO(dateStr) {
  if (!dateStr || !dateStr.trim()) return '';
  const parts = dateStr.trim().split('/');
  if (parts.length !== 3) return '';
  const [m, d, y] = parts;
  if (!m || !d || !y) return '';
  return `${y.padStart(4,'0')}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`;
}

const raw = fs.readFileSync(CSV_PATH, 'utf8');
const lines = raw.split(/\r?\n/).filter(l => l.trim());
const headers = parseCSVLine(lines[0]);

console.log('Headers:', headers);
console.log('Total data rows:', lines.length - 1);

const rows = lines.slice(1).map((line, i) => {
  const cols = parseCSVLine(line);
  const get = (name) => {
    const idx = headers.indexOf(name);
    return idx >= 0 ? (cols[idx] || '').trim() : '';
  };

  return {
    id: 900000 + i,
    first: get('First Name'),
    last: get('Last Name'),
    gender: get('Gender'),
    status: get('Status') || 'Active',
    birthday: toISO(get('Birthdate')),
    phone: get('Mobile'),
    email: get('Email'),
    address: {
      street: get('Street Address'),
      city: get('City'),
      state: get('State'),
      zip: get('Zip'),
    },
    anniversary: toISO(get('Anniversary')),
    joined: toISO(get('First Visit')) || '2026-05-19',
    type: 'Member',
    role: '',
    family: '',
    familyId: null,
    notes: '',
    spouseName: '',
    children: [],
    emergencyName: '',
    emergencyPhone: '',
    emergencyRelation: '',
    baptismDate: '',
    salvationDate: '',
    allergies: [],
    medical: [],
    medicalNotes: '',
    occupation: '',
    employer: '',
    addedBy: 'CSV Import',
    addedDate: '2026-05-19',
  };
}).filter(r => r.first && r.last); // skip blank rows

console.log('Valid records:', rows.length);

const ts = `// AUTO-GENERATED by scripts/generateMemberSeed.js — do not edit manually
// Source: Adults List.csv (${rows.length} members)
export const SEED_MEMBERS: any[] = ${JSON.stringify(rows, null, 0)};
`;

fs.writeFileSync(OUT_PATH, ts, 'utf8');
console.log('Written to', OUT_PATH);
